/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgba(var(--color-primary), 0.05)',
          100: 'rgba(var(--color-primary), 0.1)',
          200: 'rgba(var(--color-primary), 0.2)',
          300: 'rgba(var(--color-primary), 0.3)',
          400: 'rgba(var(--color-primary), 0.4)',
          500: 'rgba(var(--color-primary), 0.5)',
          600: 'rgba(var(--color-primary), 0.6)',
          700: 'rgba(var(--color-primary), 0.7)',
          800: 'rgba(var(--color-primary), 0.8)',
          900: 'rgba(var(--color-primary), 0.9)',
        },
        secondary: {
          50: 'rgba(var(--color-secondary), 0.05)',
          100: 'rgba(var(--color-secondary), 0.1)',
          200: 'rgba(var(--color-secondary), 0.2)',
          300: 'rgba(var(--color-secondary), 0.3)',
          400: 'rgba(var(--color-secondary), 0.4)',
          500: 'rgba(var(--color-secondary), 0.5)',
          600: 'rgba(var(--color-secondary), 0.6)',
          700: 'rgba(var(--color-secondary), 0.7)',
          800: 'rgba(var(--color-secondary), 0.8)',
          900: 'rgba(var(--color-secondary), 0.9)',
        },
        accent: {
          50: 'rgba(var(--color-accent), 0.05)',
          100: 'rgba(var(--color-accent), 0.1)',
          200: 'rgba(var(--color-accent), 0.2)',
          300: 'rgba(var(--color-accent), 0.3)',
          400: 'rgba(var(--color-accent), 0.4)',
          500: 'rgba(var(--color-accent), 0.5)',
          600: 'rgba(var(--color-accent), 0.6)',
          700: 'rgba(var(--color-accent), 0.7)',
          800: 'rgba(var(--color-accent), 0.8)',
          900: 'rgba(var(--color-accent), 0.9)',
        },
        success: {
          50: 'rgba(var(--color-success), 0.05)',
          100: 'rgba(var(--color-success), 0.1)',
          200: 'rgba(var(--color-success), 0.2)',
          300: 'rgba(var(--color-success), 0.3)',
          400: 'rgba(var(--color-success), 0.4)',
          500: 'rgba(var(--color-success), 0.5)',
          600: 'rgba(var(--color-success), 0.6)',
          700: 'rgba(var(--color-success), 0.7)',
          800: 'rgba(var(--color-success), 0.8)',
          900: 'rgba(var(--color-success), 0.9)',
        },
        warning: {
          50: 'rgba(var(--color-warning), 0.05)',
          100: 'rgba(var(--color-warning), 0.1)',
          200: 'rgba(var(--color-warning), 0.2)',
          300: 'rgba(var(--color-warning), 0.3)',
          400: 'rgba(var(--color-warning), 0.4)',
          500: 'rgba(var(--color-warning), 0.5)',
          600: 'rgba(var(--color-warning), 0.6)',
          700: 'rgba(var(--color-warning), 0.7)',
          800: 'rgba(var(--color-warning), 0.8)',
          900: 'rgba(var(--color-warning), 0.9)',
        },
        error: {
          50: 'rgba(var(--color-error), 0.05)',
          100: 'rgba(var(--color-error), 0.1)',
          200: 'rgba(var(--color-error), 0.2)',
          300: 'rgba(var(--color-error), 0.3)',
          400: 'rgba(var(--color-error), 0.4)',
          500: 'rgba(var(--color-error), 0.5)',
          600: 'rgba(var(--color-error), 0.6)',
          700: 'rgba(var(--color-error), 0.7)',
          800: 'rgba(var(--color-error), 0.8)',
          900: 'rgba(var(--color-error), 0.9)',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: 'rgba(var(--color-gray), 0.5)',
          600: 'rgba(var(--color-gray), 0.6)',
          700: 'rgba(var(--color-gray), 0.7)',
          800: 'rgba(var(--color-gray), 0.8)',
          900: 'rgba(var(--color-gray), 0.9)',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'scale-in': 'scaleIn 0.3s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};